### ISSUE TITLE
drivechain_client: depositing with empty address yields error message

### ISSUE THREAD

**Issue by torkelrogstad** [LayerTwo-Labs/drivechain-frontends#293]
Should prevent submission with empty field. Ideally we'd also validate the address pre-submit, but I think it's fine to defer to the backend for now. 

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/be92a00f-2d1b-418b-ade3-e146ff2b479f">

**Comment by octobocto** [comment]
i got this
