### ISSUE TITLE
Logs are written to strange location on macOS release

### ISSUE THREAD

**Issue by torkelrogstad** [LayerTwo-Labs/drivechain-frontends#85]
<img width="455" alt="image" src="https://github.com/barebitcoin/sidesail/assets/16610775/2403bdbd-de38-44b1-80ef-8eca6aa5783f">

**Comment by octobocto** [comment]
No longer the case. Works on my machine... Reopen if still an issue in the future

**Comment by torkelrogstad** [comment]
Just saw this locally 

<img width="912" alt="image" src="https://github.com/barebitcoin/sidesail/assets/16610775/93827b16-0c23-4640-9e04-5e5c951cd7eb">

**Comment by octobocto** [comment]
reopen again if still an issue:p Have moved a lot of stuff around
